name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  integration-test:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/integration-test.yml

  release:
    name: release
    runs-on: ubuntu-latest
    needs: integration-test
    environment: release
    permissions:
      contents: write # for making github release
      pull-requests: write # for commenting release version
      issues: write # for commenting release version
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Run semantic release
        uses: electron/semantic-trusted-release@5eceb399ac8de8863205cf6e34109bce473ba566 # v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
